export const ActionTypes = {
  SET_EXPERTS: 'SET_EXPERTS',
  SELECTED_EXPERT: 'SELECTED_EXPERT',
  REMOVE_SELECTED_EXPERT: 'REMOVE_SELECTED_EXPERT',
  REMOVE_HOME_EXPERTS: 'REMOVE_HOME_EXPERTS',
  HOME_EXPERTS: 'HOME_EXPERTS',
};
